sudo: false
language: php
php:
  - 5.6

env:
  - TRAVIS_NODE_VERSION="4"

cache:
  directories:
    - bower_components
    - node_modules

install:
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
  - npm install -g npm@latest
  - npm install -g bower gulp jscs
  - npm install
  - bower install
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - npm run build
  - npm run jscs
